#ifndef NPCENTITY_HPP
#define NPCENTITY_HPP

#include "Shared/Entities/Virtual/AiEntity.hpp"
#include "Shared/Util/File.hpp"

/**
 * Entity class for NPC's. Can be creatures too, but NPC's are special in that their state persists
 * CreatureEntity is for Entities that are generated by spawners or otherwise should not persist
 *
 * \ingroup Entity
 */
class NpcEntity : public AiEntity {
    /**
     * Creates the NpcEntity from the given data and data file
     */
    NpcEntity(std::string nm, EntityPosition pos, std::string gfx1, std::string gfx2);

    /**
     * Update logic to be applied before the Behavior is applied
     */
    virtual void beforeBehaviorUpdate() override {}

    /**
     * Update logic to be applied after the Behavior is applied
     */
    virtual void afterBehaviorUpdate() override {}

    /**
     * Update logic to be applied after the timer variable is updated
     */
    virtual void afterTimerUpdate() override {}

public:
    /**
     * Loads the NPC from the data file and returns a Ptr to the created object
     */
    static Entity::Ptr create(std::string dataFile);

    /**
     * Creates an NpcEntity from the given data
     */
    static Entity::Ptr create(std::string nm, EntityPosition pos, std::string gfx1, std::string gfx2);

    /**
     * vtable
     */
    virtual ~NpcEntity() = default;

    /**
     * Returns "NpcEntity"
     */
    const std::string getType() const;

	/**
	 * Notifies the Entity that they were attacked by another Entity
	 */
    void notifyAttacked(Ptr attacker, CombatAttack::ConstPtr attack);

    /**
     * Notifies the Entity of nearby combat
     */
    void notifyCombatNearby(List combatants);

    /**
     * Notifies the Entity that they were interacted with
     */
    void notifyInteracted(Ptr user);
};

#endif // NPCENTITY_HPP
